version: '3.8'
services:
  auth-services:
    build:
      context: .
      dockerfile: ./services/auth-services/Dockerfile
    ports:
      - "8001:8000"
  user-services:
    build:
      context: .
      dockerfile: ./services/user-services/Dockerfile
    ports:
      - "8002:8000"
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-services
      - user-services
secrets:
  db_password:
    file: db_password.txt
