version: '3.8'
services:
  auth-services:
    build: ./services/auth-services
    ports:
      - "8001:8001"
  user-services:
    build: ./services/user-services
    ports:
      - "8002:8002"
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
  group-services:
    build: ./services/group-services
    ports:
      - "8003:8003"
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
      USER_SERVICES_URL: http://user-services:8000/api/v1/users
    secrets:
      - db_password
  steps-services:
    build: ./services/steps-services
    ports:
      - "8004:8004"
    environment:
      DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - auth-services
      - user-services
      - group-services
      - steps-services
secrets:
  db_password:
    file: db_password.txt
