version: 2.1

orbs:
  python: circleci/python@1.5.0
  codecov: codecov/codecov@3.2.2

jobs:
  test-user-services:
    docker:
      - image: cimg/python:3.9.0
    steps:
      - checkout
      - run:
          name: Prepare files
          command: mv ./user_services/. . && pwd && ls -al
      - run: 
          name: Install dependencies
          command: pwd && ls -al && pip install -r requirements.txt
      - run:
          name: Run tests
          command: pytest --cov-config=.coveragerc --cov=app --cov-report=xml --cov-report=html test
      - codecov/upload:
          file: coverage.xml
  
workflows:
  test-all-services:
    jobs:
      - test-user-services
